# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here

np.version.version


'1.16.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))


In [4]:
# Method 2




In [5]:
# Method 3

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.74563388 0.78031935 0.83456311 0.16139016 0.7826585 ]
  [0.62355091 0.0897086  0.34887306 0.04219337 0.34744977]
  [0.35589239 0.20943741 0.48720487 0.06017736 0.14236763]]

 [[0.64107023 0.25661836 0.49341095 0.8681051  0.46130607]
  [0.7393477  0.68200255 0.68547641 0.29725052 0.09253776]
  [0.65700374 0.58028832 0.21380023 0.06855    0.29605764]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
if a.size == b.size:
    print("same")
    
else:
    print("not the same")

same


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

#print(np.add(a,b))



#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
# a 2x3x5
# b 5x2x3 
c = b.transpose(1,2,0)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = np.add(a, c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print(d)

difference_a_d = np.subtract(d,a)
print(difference_a_d)


[[[0.74563388 0.78031935 0.83456311 0.16139016 0.7826585 ]
  [0.62355091 0.0897086  0.34887306 0.04219337 0.34744977]
  [0.35589239 0.20943741 0.48720487 0.06017736 0.14236763]]

 [[0.64107023 0.25661836 0.49341095 0.8681051  0.46130607]
  [0.7393477  0.68200255 0.68547641 0.29725052 0.09253776]
  [0.65700374 0.58028832 0.21380023 0.06855    0.29605764]]]
[[[1.74563388 1.78031935 1.83456311 1.16139016 1.7826585 ]
  [1.62355091 1.0897086  1.34887306 1.04219337 1.34744977]
  [1.35589239 1.20943741 1.48720487 1.06017736 1.14236763]]

 [[1.64107023 1.25661836 1.49341095 1.8681051  1.46130607]
  [1.7393477  1.68200255 1.68547641 1.29725052 1.09253776]
  [1.65700374 1.58028832 1.21380023 1.06855    1.29605764]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = np.multiply(a,c)

print(a)
print(c)

[[[0.74563388 0.78031935 0.83456311 0.16139016 0.7826585 ]
  [0.62355091 0.0897086  0.34887306 0.04219337 0.34744977]
  [0.35589239 0.20943741 0.48720487 0.06017736 0.14236763]]

 [[0.64107023 0.25661836 0.49341095 0.8681051  0.46130607]
  [0.7393477  0.68200255 0.68547641 0.29725052 0.09253776]
  [0.65700374 0.58028832 0.21380023 0.06855    0.29605764]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
#compares shape
if e.all() == a.all():
       print("yes")
else:
    print("no")
    
#compares if all elements are the same
if np.array_equal(e, a):
       print("yes")
else:
    print("no")

yes
yes


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here

f = np.empty((2,3,5))
print(f)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here

for i in range(len(d)):
    for j in range(len(d[0])):
        for k in range(len(d[0,0])):
            el = d[i,j,k]
            if el == d_min:
                f[i,j,k] = 0
            elif el == d_max:
                f[i,j,k] = 100
            elif el == d_mean:
                f[i,j,k] = 50
            elif el < d_mean:
                f[i,j,k] = 25
            else:
                f[i,j,k] = 75

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
print(d)
print(f)

[[[1.74563388 1.78031935 1.83456311 1.16139016 1.7826585 ]
  [1.62355091 1.0897086  1.34887306 1.04219337 1.34744977]
  [1.35589239 1.20943741 1.48720487 1.06017736 1.14236763]]

 [[1.64107023 1.25661836 1.49341095 1.8681051  1.46130607]
  [1.7393477  1.68200255 1.68547641 1.29725052 1.09253776]
  [1.65700374 1.58028832 1.21380023 1.06855    1.29605764]]]
[[[ 75.  75.  75.  25.  75.]
  [ 75.  25.  25.   0.  25.]
  [ 25.  25.  75.  25.  25.]]

 [[ 75.  25.  75. 100.  75.]
  [ 75.  75.  75.  25.  25.]
  [ 75.  75.  25.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here